name: sequences
description: Sequences, by Christian Lawson-Perfect

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
